name: Flutter Build CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch: # Allows you to manually trigger the workflow from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
          cache: true

      - name: Check Flutter version
        run: flutter --version

      - name: Scaffolding missing platform directories
        run: flutter create --org com.attendance.camu --project-name camu_attendance .

      - name: Update Kotlin Version
        run: |
          if [ -f "android/settings.gradle" ]; then
            sed -i -E 's/id "org.jetbrains.kotlin.android" version "[0-9\.]*" apply false/id "org.jetbrains.kotlin.android" version "1.9.24" apply false/g' android/settings.gradle
          fi
          if [ -f "android/build.gradle" ]; then
            sed -i 's/ext.kotlin_version =.*/ext.kotlin_version = "1.9.24"/g' android/build.gradle
          fi

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK (Release)
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7
